### PR TITLE
Provide helper class to help set CDN server

### PR DESCRIPTION
**Pull request by astrofrog**
The aim of this PR is to provide a central place (``URLHelpers``) where we set/patch the domain for URLs, which allows us to switch the URLs to use e.g. beta.worldwidetelescope.org if the current protocol is https.

In future we could also provide API calls to change the domains to use on-the-fly.

### CODE REVIEW

**Comment by astrofrog** [comment]
@pkgw - this seems to work, and the only errors I now see in the console are related to ``Access-Control-Allow-Origin``, e.g:

```
Failed to load resource: ... Origin https://localhost:4443 is not allowed by Access-Control-Allow-Origin```

This would work properly if on beta.worldwidetelescope.org though

**Comment by pkgw** [comment]
Hmm, did you see `GetProxiedUrl()` in `wwtlib/Util.cs`? It also does URL rewriting, mainly to (as the name says) shim in the CORS proxy when relevant. The tests in that function are, I think, currently busted; I restructured things in WorldWideTelescope/wwt-webgl-engine#1, which is a repo that splits out the WebGL rendering engine backend from the webclient app frontend.

**Comment by astrofrog** [comment]
@pkgw - I'm not sure what the best way is to move forward with this given your work on wwt-webgl-engine - do you want me to copy over some of the restructuring you did there to this PR? At the moment I had got rid of all CORS errors *but* that was with a very minimal use of the SDK so many URLs were probably not being hit. Do you have more complete examples of use of the SDK that might highlight issues?

**Comment by pkgw** [comment]
As per conversation with @astrofrog, closing this as superseded by the work in the new `wwt-webgl-engine` repo, e.g. WorldWideTelescope/wwt-webgl-engine#10.

**Pull request closed without merging**
